baseurl      = "https://harshitm98.github.io/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"
googleAnalytics = 'G-MTVN5X7DXW'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Pentester | Grad student at CMU | OSCP"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = ""
  keywords = "homepage, blog"
  images = [""]
  [[params.social]]
    name = "github"
    url = "https://github.com/harshitm98/"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/harshitm98/"
  
  [[params.social]]
    name = "hackthebox"
    url = "https://app.hackthebox.com/profile/299979"

  [[params.social]]
    name = "tryhackme"
    url = "https://www.tryhackme.com/p/fakebatman"

  [[params.social]]
    name = "email"
    url = "mailto:hsmahesh@andrew.cmu.edu"



    

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Harshit Maheshwari"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/fakebatman"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
